version: '3.8'
services:
  oracle23ai:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-ml-auto-indexing
    ports:
      - 1521:1521
    environment:
      - ORACLE_PWD=Oracle123
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./scripts:/opt/oracle/scripts/startup
volumes:
  oracle-data:
